### ISSUE TITLE
Hide select option value 

### ISSUE THREAD

**Issue by MsFoued** [techouse/select-auto-complete#6]
![tempsnip](https://user-images.githubusercontent.com/15153313/58470578-465f8300-8142-11e9-8bce-872c856421a5.png)

`SelectAutoComplete::make('Origin market', 'origin_market')
            ->options(collect($mergedMarketsOptions)->mapWithKeys(function ($option) {
              return [$option['code'] => $option['name']];
            }))->default(["value" => $this->origin_market])->displayUsingLabels()->hideFromIndex(),`

Is it possible to hide option values  referred to `$option['code']` in the above code ?

**Comment by techouse** [comment]
Thanks for bringing this to my attention! Apparently the `displayUsingLabels()` method didn't work out of the box with [vue-single-select](https://github.com/robrogers3/vue-single-select#readme) so I fixed it in [v1.1.1](https://github.com/techouse/select-auto-complete/commit/3005d3697a75da6186a509628190539d7e6513f4)

**Comment by bernhardh** [comment]
I have made a fresh install of your package and still getting this error. I am on version `v1.2.3`

**Comment by techouse** [comment]
Hmm, what does your JSON look like?

**Comment by bernhardh** [comment]
For example:

```
{
    "component": "select-auto-complete",
    "prefixComponent": true,
    "indexName": "Sortierfeld",
    "name": "Sortierfeld",
    "attribute": "order_by",
    "value": null,
    "panel": null,
    "sortable": false,
    "nullable": false,
    "readonly": false,
    "required": false,
    "textAlign": "left",
    "sortableUriKey": "order_by",
    "stacked": false,
    "bmdevClasses": {
        "editContainer": "w-full md:w-1\/3"
    },
    "maxResults": 30,
    "maxHeight": "220px",
    "options": [{
        "label": "Hits Aktuell",
        "value": "hits_akt"
    }, {
        "label": "\u00c4nderungsdatum",
        "value": "updated_at"
    }]
}
```

Btw. since I am using multiple selectboxes, I also get an warning in the console:

![image](https://user-images.githubusercontent.com/642292/71888363-43992780-3140-11ea-81f0-c4c3bdab30cb.png)

**Comment by techouse** [comment]
Thanks for the JSON :)

So if I understand you correctly you want to display it only with labels and have used the `displayUsingLabels` option which [should only display labels](https://github.com/techouse/select-auto-complete/blob/180cc5a6a1cd844f01a39f8f05d88f623d99ed19/resources/js/components/Form/index.vue#L104) but it doesn't?

Regarding the same `id`s I'm not sure as to why it does that since if you look in [resources/js/components/Form/index.vue on line 4](https://github.com/techouse/select-auto-complete/blob/master/resources/js/components/Form/index.vue#L4) it clearly sets the `id` dynamically. Weird.

**Comment by bernhardh** [comment]
Oh. Didn't get the `displayUsingLabels` method, since I thought showing the label for the label would be the default behavior :D.

**Comment by techouse** [comment]
Hehe, you are correct it is a bit vaguely documented. I will update the README to make it more visible.
